sources:
    - name: noodles
      handler:
          graphql:
              endpoint: ${GRAPH_API_URL}
      transforms:
          - autoPagination:
            validateSchema: true
documents:
    - "./documents/**/*.graphql"